<template>
<div class="row justify-content-center no-gutters">
  <div class="col-12 col-sm-8 col-md-8 col-lg-6">
    <section>
      <div class="container">
        <div class="row">
          <div class="col">
            <h1>Privacy Policy</h1>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <p class="c16"><span class="c19 c2"></span></p>
            <p class="c18"><span class="c2 c25">Effective date: </span><span class="c10">2/17/2016</span></p>
            <p class="c1"><span class="c6 c2"></span></p>
            <p class="c3"><span class="c6 c2">We at Racepass know you care about how your personal information is used and shared, and we take your privacy seriously. &nbsp;Please read the following to learn more about our Privacy Policy. &nbsp;</span><span class="c0">By using or accessing the Services in any manner, you acknowledge that you accept the practices and policies outlined in this Privacy Policy, and you hereby consent that we will collect, use, and share your information in the following ways.</span><span class="c6 c2">&nbsp;</span></p>
            <p class="c18"><span class="c2 c25">Remember that your</span><span class="c2">&nbsp;use of Racepass&rsquo;s Services is at all times subject to the </span><span class="c7 c17"><router-link class="c8" to="/terms">Terms of Use</router-link></span><span class="c2">, which incorporates this Privacy Policy. &nbsp;Any terms we use in this Policy without defining them have the definitions given to them in the </span><span class="c7"><router-link class="c8" to="/terms">Terms of Use</router-link></span><span class="c6 c2">. &nbsp;</span></p>
            <p class="c1"><span class="c6 c2"></span></p>
            <p class="c4"><span class="c19 c2">What does this Privacy Policy cover</span><span class="c0">?</span></p>
            <p class="c3"><span class="c6 c2">This Privacy Policy covers our treatment of personally identifiable information (&quot;Personal Information&quot;) that we gather when you are accessing or using our Services, but not to the practices of companies we don&rsquo;t own or control, or people that we don&rsquo;t manage. &nbsp;We gather various types of Personal Information from our users, as explained in more detail below, and we use this Personal Information internally in connection with our Services, including to personalize, provide, and improve our services, to allow you to set up a user account and profile, to contact you and allow other users to contact you, to fulfill your requests for certain products and services, and to analyze how you use the Services. In certain cases, we may also share some Personal Information with third parties, but only as described below. </span></p>
            <p class="c9"><span class="c6 c2">As noted in the </span><span class="c7"><router-link class="c8" to="/terms">Terms of Use</router-link></span><span class="c6 c2">, we do not knowingly collect or solicit personal information from anyone under the age of 13. If you are under 13, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn that we have collected personal information from a child under age 13, we will delete that information as quickly as possible. If you believe that a child under 13 may have provided us personal information, please contact us at </span><span class="c7"><a class="c8" href="mailto:info@racepass.com">info@racepass.com</a></span><span class="c6 c2">.</span></p>
            <p class="c9"><span class="c19 c2">Will Racepass ever change this Privacy Policy</span><span class="c0">?</span></p>
            <p class="c3"><span class="c6 c2">We&rsquo;re constantly trying to improve our Services, so we may need to change this Privacy Policy from time to time as well, but we will alert you to changes by placing a notice on racepass.com, by sending you an email, and/or by some other means. Please note that if you&rsquo;ve opted not to receive legal notice emails from us (or you haven&rsquo;t provided us with your email address), those legal notices will still govern your use of the Services, and you are still responsible for reading and understanding them. &nbsp;If you use the Services after any changes to the Privacy Policy have been posted, that means you agree to all of the changes. &nbsp;Use of information we collect now is subject to the Privacy Policy in effect at the time such information is collected.</span></p>
            <p class="c9"><span class="c19 c2">What Information does Racepass Collect</span><span class="c0">?</span></p>
            <p class="c3"><span class="c2 c13">Information You Provide to Us:</span></p>
            <p class="c3"><span class="c6 c2">We receive and store any information you knowingly provide to us. &nbsp;For example, through the registration process and/or through your account settings, we may collect Personal Information such as your name, email address, phone number, and third-party account credentials (for example, your log-in credentials for Facebook or other third party sites). If you provide your third-party account credentials to us [or otherwise sign in to the Services through a third party site or service, you understand some content and/or information in those accounts (&ldquo;Third Party Account Information&rdquo;) may be transmitted into your account with us, and that Third Party Account Information transmitted to our Services is covered by this Privacy Policy; for example, </span><span class="c10">login through oAuth tools provided by third party services (e.g., Facebook or Strava).</span><span class="c6 c2">&nbsp; </span><span class="c6 c2">Certain information may be required to register with us or to take advantage of some of our features. &nbsp;</span></p>
            <p class="c3"><span class="c6 c2">We may communicate with you if you&rsquo;ve provided us the means to do so. For example, if you&rsquo;ve given us your email address, we may send you promotional email offers on behalf of other businesses, or email you about your use of the Services. &nbsp;Also, we may receive a confirmation when you open an email from us. This confirmation helps us make our communications with you more interesting and improve our services. If you do not want to receive communications from us, please indicate your preference by </span><span class="c10">emailing info@racepass.com</span><span class="c6 c2">. &nbsp;</span></p>
            <p class="c3"><span class="c13 c2">Information Collected Automatically</span></p>
            <p class="c3"><span class="c6 c2">Whenever you interact with our Services, we automatically receive and record information on our server logs from your browser or device, which may include your IP address, geolocation data, device identification, &ldquo;cookie&rdquo; information, the type of browser and/or device you&rsquo;re using to access our Services, and the page or feature you requested. &ldquo;Cookies&rdquo; are identifiers we transfer to your browser or device that allow us to recognize your browser or device and tell us how and when pages and features in our Services are visited and by how many people. &nbsp;You may be able to change the preferences on your browser or device to prevent or limit your device&rsquo;s acceptance of cookies, but this may prevent you from taking advantage of some of our features. &nbsp;</span></p>
            <p class="c3"><span class="c6 c2">Our advertising partners may also transmit cookies to your browser or device, when you click on ads that appear on the Services. Also, &nbsp;if you click on a link to a third party website or service, a third party may also transmit cookies to you. &nbsp;Again, this Privacy Policy does not cover the use of cookies by any third parties, and we aren&rsquo;t responsible for their privacy policies and practices. &nbsp;Please be aware that cookies placed by third parties may continue to track your activities online even after you have left our Services, and those third parties may not honor &ldquo;Do Not Track&rdquo; requests you have set using your browser or device.</span></p>
            <p class="c3"><span class="c6 c2">We may use this data to customize content for you that we think you might like, based on your usage patterns. &nbsp;We may also use it to improve the Services &ndash; for example, this data can tell us how often users use a particular feature of the Services, and we can use that knowledge to make the Services interesting to as many users as possible. &nbsp; </span></p>
            <p class="c3"><span class="c13 c2">Information Collected From Other Websites and Do Not Track Policy</span></p>
            <p class="c3"><span class="c6 c2">Through cookies we place on your browser or device, we may collect information about your online activity after you leave our Services. &nbsp;Just like any other usage information we collect, this information allows us to improve the Services and customize your online experience, and otherwise as described in this Privacy Policy. &nbsp;Your browser may offer you a &ldquo;Do Not Track&rdquo; option, which allows you to signal to operators of websites and web applications and services (including behavioral advertising services) that you do not wish such operators to track certain of your online activities over time and across different websites. &nbsp;Our Services do not support Do Not Track requests at this time, which means that we collect information about your online activity both while you are using the Services and after you leave our Services.</span></p>
            <p class="c3"><span class="c2 c19">Will Racepass Share Any of the Personal Information it Receives</span><span class="c0">?</span></p>
            <p class="c3"><span class="c6 c2">We do not rent or sell your Personal Information in personally identifiable form to anyone. We may share your Personal Information with third parties as described in this section:</span></p>
            <p class="c9"><span class="c0">Information that&rsquo;s been de-identified. &nbsp;</span><span class="c6 c2">We may de-identify your Personal Information so that you are not identified as an individual, and provide that information to our partners. We may also provide aggregate usage information to our partners (or allow partners to collect that information from you), who may use such information to understand how often and in what ways people use our Services, so that they, too, can provide you with an optimal online experience. However, we never disclose aggregate usage or de-identified information to a partner (or allow a partner to collect such information) in a manner that would identify you as an individual </span><span class="c6 c2">person</span><span class="c6 c2">.</span></p>
            <p class="c9"><span class="c0">At your direction:</span><span class="c6 c2">&nbsp;When you use our Services to sign up for races or other events, products or services hosted or provided by third parties, we may provide certain personal information to those third parties in order to enable such sign ups. &nbsp;Such third parties&rsquo; use of your personal information is not under Racepass&rsquo;s control, and may be subject to the separate privacy policies of such third parties.</span></p>
            <p class="c9"><span class="c0">Advertisers:</span><span class="c6 c2">&nbsp;We allow advertisers and/or merchant partners (&ldquo;Advertisers&rdquo;) to choose the demographic information of users who will see their advertisements and/or promotional offers and you agree that we may provide any of the information we have collected from you in non-personally identifiable form to an Advertiser, in order for that Advertiser to select the appropriate audience for those advertisements and/or offers. For example, we might use the fact you are located in San Francisco to show you ads or offers for San Francisco businesses, but we will not tell such businesses who you are. &nbsp;Or, we might allow Advertisers to display their ads to users with similar usage patterns to yours, but we will not disclose usage information to Advertisers except in aggregate form, and not in a manner that would identify you personally. &nbsp;Note that if an advertiser asks us to show an ad to a certain audience or audience segment and you respond to that ad, the advertiser may conclude that you fit the description of the audience they were trying to reach.</span></p>
            <p class="c9"><span class="c6 c2">We may deliver a file to you through the Services (known as a &ldquo;web beacon&rdquo;) from an ad network. &nbsp;Web beacons allow ad networks to provide anonymized, aggregated auditing, research and reporting for us and for advertisers. &nbsp;Web beacons also enable ad networks to serve targeted advertisements to you when you visit other websites. &nbsp;Because your web browser must request these advertisements and web beacons from the ad network&rsquo;s servers, these companies can view, edit, or set their own cookies, just as if you had requested a web page from their site. &nbsp;You may be able to opt-out of web beacon tracking conducted by third parties through our Services by adjusting the Do Not Track settings on your browser; please note that we don&rsquo;t control whether or how these third parties comply with Do Not Track requests.</span></p>
            <p class="c3"><span class="c0">Affiliated Businesses:</span><span class="c6 c2">&nbsp;In certain situations, businesses or third party websites we&rsquo;re affiliated with may sell or provide products or services to you through or in connection with the Services (either alone or jointly with us). &nbsp;You can recognize when an affiliated business is associated with such a transaction or service, and we will share your Personal Information with that affiliated business only to the extent that it is related to such transaction or service. One such service may include the ability for you to automatically transmit Third Party Account Information to your Services profile or to automatically transmit information in your Services profile to your third party account; for example, </span><span class="c10">loading your finishing times or inviting friends on Facebook</span><span class="c6 c2">.</span><span class="c6 c2">&nbsp;</span><span class="c6 c2">We have no control over the policies and practices of third party websites or businesses as to privacy or anything else, so if you choose to take part in any transaction or service relating to an affiliated website or business, please review all such business&rsquo; or websites&rsquo; policies.</span></p>
            <p class="c3"><span class="c0">Agents:</span><span class="c6 c2">&nbsp;We employ other companies and people to perform tasks on our behalf and need to share your information with them to provide products or services to you; for example, we may use a payment processing company to receive and process your credit card transactions for us. Unless we tell you differently, our agents do not have any right to use the Personal Information we share with them beyond what is necessary to assist us. Note that an &ldquo;agent&rdquo; may also be considered a &ldquo;partner&rdquo; in certain circumstances, and would be subject to the terms of the &ldquo;</span><span class="c0">Information that&rsquo;s been de-identified</span><span class="c6 c2">&rdquo; section in that regard.</span></p>
            <p class="c9"><span class="c0">User Profiles and Submissions:</span><span class="c2 c20">&nbsp;</span><span class="c6 c2">Certain user profile information, including your name, location, and any video or image content that such user has uploaded to the Services, may be displayed to other users to facilitate user interaction within the Services or address your request for our services. &nbsp;Your account privacy settings may allow you to limit the other users who can see the Personal Information in your user profile and/or what information in your user profile is visible to others. &nbsp;Please remember that any content you upload to your public user profile, along with any Personal Information or content that you voluntarily disclose online in a manner other users can view (on discussion boards, in messages and chat areas, etc.) becomes publicly available, and can be collected and used by anyone. &nbsp;Your user name may also be displayed to other users if and when you send messages or comments or upload images or videos through the Services and other users can contact you through messages and comments. </span><span class="c6 c2">Additionally, if you sign into the Services through a third party social networking site or service, your list of &ldquo;friends&rdquo; from that site or service may be automatically imported to the Services, and such &ldquo;friends,&rdquo; if they are also registered users of the Services, may be able to access certain non-public information you have entered in your Services user profile. &nbsp;Again, we do not control the policies and practices of any other third party site or service.</span></p>
            <p class="c3"><span class="c0">Business Transfers:</span><span class="c6 c2">&nbsp;We may choose to buy or sell assets, and may share and/or transfer customer information in connection with the evaluation of and entry into such transactions.</span><span class="c2 c25 c28">&nbsp;</span><span class="c6 c2">Also, if we (or our assets) are acquired, or if we go out of business, enter bankruptcy, or go through some other change of control, Personal Information could be one of the assets transferred to or acquired by a third party. </span></p>
            <p class="c3"><span class="c0">Protection of Racepass and Others:</span><span class="c6 c2">&nbsp;We reserve the right to access, read, preserve, and disclose any information that we [reasonably] believe is necessary to comply with law or court order; enforce or apply our </span><span class="c26 c2 c27"><router-link class="c8" to="/terms">Terms of Use</router-link></span><span class="c6 c2">&nbsp;</span><span class="c6 c2">and other agreements; or protect the rights, property, or safety of Racepass, our employees, our users, or others. &nbsp;</span></p>
            <p class="c3"><span class="c19 c2">Is Personal Information about me secure</span><span class="c0">?</span></p>
            <p class="c3"><span class="c6 c2">Your account is protected by a password for your privacy and security</span><span class="c6 c2">.</span><span class="c10">&nbsp;</span><span class="c6 c2">If you access your account via a third party site or service, you may have additional or different sign-on protections via that third party site or service.</span><span class="c6 c2">&nbsp; You must prevent unauthorized access to your account and Personal Information by selecting and protecting your password </span><span class="c6 c2">and/or other sign-on mechanism</span><span class="c6 c2">&nbsp;</span><span class="c6 c2">appropriately and limiting access to your computer or device and browser by signing off after you have finished accessing your account.</span></p>
            <p class="c9"><span class="c6 c2">We endeavor to protect the privacy of your account and other Personal Information we hold in our records, but unfortunately, we cannot guarantee complete security. &nbsp;Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time. </span></p>
            <p class="c9"><span class="c19 c2">What Personal Information can I access</span><span class="c0">?</span></p>
            <p class="c18"><span class="c6 c2">Through your account settings, you may access, and, in some cases, edit or delete the following information you&rsquo;ve provided to us:</span></p>
            <p class="c1 c5"><span class="c6 c2"></span></p>
            <ul class="c15 lst-kix_list_5-0 start">
              <li class="c14"><span class="c6 c2">name and password</span></li>
              <li class="c14"><span class="c6 c2">email address</span></li>
              <li class="c14"><span class="c6 c2">location</span></li>
              <li class="c14"><span class="c6 c2">user profile information, including images and other content you have uploaded to the site</span></li>
            </ul>
            <p class="c1 c5"><span class="c6 c2"></span></p>
            <p class="c4"><span class="c6 c2">The information you can view, update, and delete may change as the Services change. &nbsp;If you have any questions about viewing or updating information we have on file about you, please contact us at </span><span class="c10">info@racepass.com</span><span class="c6 c2">.</span><span class="c6 c2">&nbsp;</span></p>
            <p class="c1"><span class="c6 c2"></span></p>
            <p class="c4"><span class="c6 c2">Under California Civil Code Sections 1798.83-1798.84, California residents are entitled to contact us to prevent disclosure of Personal Information to third parties for such third parties&rsquo; direct marketing purposes; in order to submit such a request, please contact us at </span><span class="c10">info@racepass.com</span><span class="c6 c2">.</span></p>
            <p class="c4 c24"><span class="c6 c2"></span></p>
            <p class="c4"><span class="c19 c2">What choices do I have</span><span class="c0">?</span></p>
            <p class="c3"><span class="c6 c2">You can always opt not to disclose information to us, but keep in mind some information may be needed to register with us or to take advantage of some of our features.</span></p>
            <p class="c3"><span class="c6 c2">You may be able to add, update, or delete information as explained above. &nbsp;When you update information, however, we may maintain a copy of the unrevised information in our records. &nbsp;You may request deletion of your account by </span><span class="c10">emailing info@racepass.com</span><span class="c6 c2">.</span><span class="c6 c2">&nbsp;Some information may remain in our records after your deletion of such information from your account. We may use any aggregated data derived from or incorporating your Personal Information after you update or delete it, but not in a manner that would identify you personally. &nbsp;</span></p>
            <p class="c4"><span class="c19 c2">What if I have questions about this policy?</span></p>
            <p class="c4"><span class="c6 c2">If you have any questions or concerns regarding our privacy policies, please send us a detailed message to </span><span class="c10">info@racepass.com</span><span class="c6 c2">, and we will try to resolve your concerns.</span></p>
            <p class="c1"><span class="c6 c2"></span></p>
            <p class="c4 c24"><span class="c6 c2"></span></p>
            <div>
              <p class="c18"><span class="c6 c17 c29">GDSVF&amp;H\2737097.1</span><span class="c11">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
              <p class="c12"><span class="c6 c23 c17"></span></p>
            </div>

          </div>
        </div>
      </div>
    </section>
  </div>
</div>
</template>

<script>
export default {
  name: 'rp-privacy'
}
</script>

<style scoped>
section a {
  color: #0EC487 !important;
}

li {
  font-size: 14px !important;
}
</style>
